# Generated by Django 3.2.9 on 2021-12-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_datatypes_restrictions_schema_schematypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('domain_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('integer', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
