# Generated by Django 3.2.9 on 2021-12-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_datasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma(,)'), ('\t', 'Tab'), ('|', 'Pipe(|)'), (';', 'Semicolon(;)')], default='Comma(,)', max_length=20),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')")], default='Double-quote(")', max_length=20),
        ),
    ]
