# Generated by Django 3.2.9 on 2021-12-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_auto_20211205_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatypes',
            options={'ordering': ['data_type'], 'verbose_name_plural': 'DataTypes'},
        ),
        migrations.RemoveField(
            model_name='schematypes',
            name='restriction',
        ),
        migrations.AddField(
            model_name='schematypes',
            name='range_from',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='schematypes',
            name='range_to',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Restrictions',
        ),
    ]
