# Generated by Django 3.2.9 on 2021-12-07 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_auto_20211205_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schematypes',
            options={'verbose_name_plural': 'SchemaTypes'},
        ),
        migrations.AddField(
            model_name='datatypes',
            name='api_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma(,)'), ('|', 'Pipe(|)'), (';', 'Semicolon(;)')], default='Comma(,)', max_length=20),
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=128)),
                ('status', models.CharField(default='Processing', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='schemas.schema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
