# Generated by Django 3.2.9 on 2021-12-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_alter_dataset_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
