# Generated by Django 3.2.9 on 2021-12-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0011_auto_20211222_1640'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schema',
            unique_together={('user', 'name')},
        ),
    ]
